name: Static analysis - phpstan

on:
  pull_request:
    paths:
      - '**.php'

jobs:
  phpstan:
    runs-on: ubuntu-20.04

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: "json,memcached"
          ini-values: "memory_limit=-1"
          coverage: none

      - name: Checkout target branch
        uses: actions/checkout@v2

      - name: 'Install project dependencies'
        run: |
          composer update --no-interaction --prefer-dist --optimize-autoloader --prefer-stable

      - name: phpstan
        run: |
          ./vendor/bin/phpstan --no-interaction --no-progress
